#! /bin/bash

sync; echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null && sudo swapoff -a && sudo swapon -a
echo "===========================================================================================" | lolcat
echo "Cache Cleaned" | lolcat
echo "===========================================================================================" | lolcat
sudo free -h | lolcat
echo "===========================================================================================" | lolcat
